# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cory Engdahl
email: cjengdahl@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello, my name is Cory. I like to tinker with code, electronics,
  and other crafts of an engineer. And now I’m starting to write
  about these things… Don’t expect anything too eloquent.
  This is site is more for me than it is for you.
  Nonetheless, if you have something to say about any of
  my posts or projects, I’m all ears.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cjengdahl.github.io"

author:
  name: C. Engdahl

# Build settings
markdown:   kramdown
include:
  - _pages
permalink: /:year-:month-:day/:title
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Assets
sass:
  sass_dir: _sass
  style: compressed


# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus: jekyll-tale

# Google Analytics
google_analytics:   UA—XXXXXXXX-X

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
